### ISSUE TITLE
Resolve Build Issues As Reported By Ashleyy

### ISSUE THREAD

**Issue by Pseudo-64** [Team-Yasogaya/SummerLove#46]
Created this issue as a bug report,, just so we don't forget to solve this later.
Here's the screenshot that ashleyy provided. 

![Image](https://github.com/Team-Yasogaya/SummerLove/assets/92845232/323fb71d-196c-4742-98cf-83432cf2b6b1)

![Image](https://github.com/Team-Yasogaya/SummerLove/assets/92845232/44e48df7-b2f7-43bd-b683-d51ff7412164)

**Comment by DaniBiga** [comment]
A Unity Editor lib was somehow included in some script headers with no purpose; solved now
